### ISSUE TITLE
Compilation Warning: Implicit Declaration of 'yylex' and 'yyerror'

### ISSUE THREAD

**Issue by ottobricks** [rabishah/Mini-C-Compiler-using-Flex-And-Yacc#2]
To reproduce, just run 'make' within the project directory or follow instructions in 'README' file.
![gcc_compile_warning](https://user-images.githubusercontent.com/22245994/64492727-7f34eb00-d24d-11e9-8497-446d05b56e1b.png)

**Comment by ottobricks** [comment]
To solve this, just declare both functions at the top of your 'c.y' file.
`%{
#include <stdio.h>
#include <stdlib.h>

extern FILE *fp;

int yylex();
void yyerror(const char *s);

%}`

That should seal the deal.

**Comment by Issam-seghir** [comment]
i add

**Comment by OmSDeshmukh** [comment]
Thanks for the help
